const Globals = {
	ID_NOT_FOUND: -1000,
	MORE_THAN_ONE: -1001,
	UNIQUE_ID: 1002,

	ACTIVAR: 'ACT',
	DELETE: 'DEL',
	DESACTIVAR: 'INA',
  ANULAR: 'ANU',

  PRINCIPAL: 'PRI',
  BORRADOR: 'BOR',
  SECONDARY: 'SEC',

  CLIENTE: 'CLI',
  PROVEEDOR: 'PRO',
  CLIENTEPROVEEDOR: 'CLP',

  SI: 'S',
  NO: 'N',

  HOY: '01',
  SEMANA: '02',
  MES: '03',
  ANUAL: '04',

  BOLETA: 'BOLETA',
  FACTURA: 'FACTURA',
  NOTA_DEB: 'NOTA_DEB',
  NOTA_CRED: 'NOTA_CRED',
  ANULACION: 'ANULACION',
  RESUMEN: 'RESUMEN',

  FACTURA_DOC_BASE: '01',
  BOLETA_DOC_BASE:'03',
  NOTAS_CREDITO_DOC_BASE:'07',
  NOTAS_DEBITO_DOC_BASE:'08',
  ANULACIONES_DOC_BASE:'RA',
  RESUMENES_DOC_BASE:'RC',

  NOTAS_NUMERACION_FACTURA:'NF',
  NOTAS_NUMERACION_BOLETA:'NB',

  ID_WELCOME_EMAIL_TEMPLATE: 2,
  ID_FORGOTTEN_EMAIL_TEMPLATE: 1,
  ID_INVOICE_EMAIL_TEMPLATE: 3,
  ID_BOLETA_EMAIL_TEMPLATE: 4,
  ID_NOTA_CRED_EMAIL_TEMPLATE: 5,
  ID_NOTA_DEB_EMAIL_TEMPLATE: 6,
  ID_ANULACION_EMAIL_TEMPLATE: 7,
  ID_WELCOME_NEW_USER: 8,
  ID_RESUMEN_EMAIL_TEMPLATE: 9,

  I_STATUS_INITIAL: 0,
  I_STATUS_INITIAL_PDF: 0,
  I_STATUS_INITIAL_XML: 1,
  I_STATUS_SUCCESS: 10,

  S_DOCUMENT_CLASS_FACTURA: 'FACTURA',
  S_DOCUMENT_CLASS_BOLETA: 'BOLETA',
  S_DOCUMENT_CLASS_NOTA_CRED: 'NOTA_CRED',
  S_DOCUMENT_CLASS_NOTA_DEB: 'NOTA_DEB',
  S_DOCUMENT_CLASS_ANULACION: 'ANULACION',
  S_DOCUMENT_CLASS_RESUMEN: 'RESUMEN',
  S_DOCUMENT_CLASS_USUARIO: 'Usuario',

  CODIGO_BASE_FACTURA: '01',
  CODIGO_BASE_BOLETA: '03',
  CODIGO_BASE_TIPO_DOCUMENTO: '07',
  CODIGO_BASE_TIPO_MOTIVO: '02',

  CODIGO_RUC: '6',

  ZEROES: '00000000',
  ZEROES_ANULACION: '00000',

  DEFAULT_PASSWORD: 'admin',

  XML: 'XML',
  PDF: 'PDF',

  NAME_NOTA_CRED: 'N. Crédito',
  NAME_NOTA_DEB: 'N. Débito',
  NAME_FACTURA: 'Factura',
  NAME_BOLETA: 'Boleta',

  //Mensajes
  MESSAGE_CREACION_PLURAL: 'han sido guardados.',
  MESSAGE_CREACION_SINGULAR_M: 'ha sido guardado.',
  MESSAGE_CREACION_SINGULAR_F: 'ha sido guardada.',

  MESSAGE_ACTUALIZACION_PLURAL: 'han sido actualizados.',
  MESSAGE_ACTUALIZACION_SINGULAR_M: 'ha sido actualizado.',
  MESSAGE_ACTUALIZACION_SINGULAR_F: 'ha sido actualizada.',

  MESSAGE_ELIMINACION_PLURAL: 'han sido eliminados.',
  MESSAGE_ELIMINACION_SINGULAR_M: 'ha sido eliminado.',
  MESSAGE_ELIMINACION_SINGULAR_F: 'ha sido eliminada.',

  MESSAGE_ESTADO_SINGULAR_M: 'ha sido cambiado.',
  MESSAGE_ESTADO_SINGULAR_F: 'ha sido cambiada.',

  DB_ILIKE: 'ILIKE',
  DB_BETWEEN: 'BETWEEN',
  DB_IN: 'IN',

  COMPROBANTE_MODULE: 'COM',
  NOTA_MODULE: 'NOT',
  ANULACION_MODULE: 'ANU',

  ALMACEN_PRINCIPAL: 'ALMPRI',

  TIPO_DOCUMENTO_SIN_RUC: '0',
  TIPO_DOCUMENTO_DNI: '1',
  TIPO_DOCUMENTO_CARNET: '4',
  TIPO_DOCUMENTO_RUC: '6',
  TIPO_DOCUMENTO_PASAPORTE: '7',
  TIPO_DOCUMENTO_CDI: 'A',

  CODIGO_BASE_PAIS: 'PE',
  CODIGO_BASE_UBIGEO: '040101',

  CODIGO_TRIBUTO_GRAVADAS: '1000',
  CODIGO_TRIBUTO_INAFECTAS: '9998',
  CODIGO_TRIBUTO_EXONERADAS: '9997',
  CODIGO_TRIBUTO_GRATUITAS: '9996',
  CODIGO_TRIBUTO_ISC: '2000',
  CODIGO_TRIBUTO_OTRO: '9999',

  GRAVADO_OPERACION_ONEROSA: '10',
  EXONERADO_OPERACION_ONEROSA: '20',
  INAFECTO_OPERACION_ONEROSA: '30'
};

module.exports = Globals;
