const Regex = {
  timestampFormat: /^[0-9]{13}$/,
  serieFacturaFormat: /^F[0-9A-Z]{3}$/,
  serieBoletaFormat: /^B[0-9A-Z]{3}$/,
  serieNotaFormat: /^[FB][0-9A-Z]{3}$/,
  serieFacturaAndBorradorFormat: /^F[0-9]{3}$/,
  numeroCorrelativoFormat: /^[0-9]{8}$/,
  numeroCorrelativoFormatAnulacionResumen: /^[0-9]{5}$/,
  codigoLocalFormat: /^[0-9]{4}$/,
  numeroIdentificacionFormat: /^[0-9A-Z]{8,15}$/,
  emailFormat: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  celularFormat: /^9[0-9]{8}$/,
  telefonoFijoFormat: /^[1-9][0-9]{5,6}$|^01-{0,1}[0-9]{7}$|^0[0-9]{2}-{0,1}[0-9]{6}$/,
  descrObserNotasLength: 200,
  descripcionFactBolNota: 250,
  razonSocialNombreLength: 100,
  direccionLength: 100,
  decimalPorcentajeNoImpuestoNumber: 2,
  codigoLocalLength: 4,
  decimalPorcentajeImpuestoNumber: 5,
  decimalMultiplicadorNumber: 3,
  codigoTablaLength: 50,
  estadoTablaLength: 3,
  numeroIdentificacionLength: 15,
  correoElectronicoLength: 150,
  telefonoCelularLength: 10,
  nombreTablaLength: 100,
  archivoLength: 150,
  numeroDecimal: true,
  tipoTablaLength: 3,
  nombreContactoLength: 100,
  codigoBaseUbigeoLength: 10,

};

module.exports = Regex;
